In [ ]:
%pip install pandas

In [ ]:
import pandas as pd
series_with_index = pd.Series([10, 20, 30, 40, 50], index=["x", "y", "z", "w", "q"])
series_with_index

In [ ]:
series_with_index["w"]

In [ ]:
series_with_index.iloc[0]

In [ ]:
series_with_index.loc["x": "z"]

In [ ]:
series_with_index[series_with_index > 25]

In [ ]:
names_series = pd.Series(names)
companies_series = pd.Series(companies)
experience_levels_series = pd.Series(experience_levels)

In [ ]:
experience_levels_series.unique()

In [ ]:
companies_series.nunique()

In [ ]:
companies_count = companies_series.value_counts()
companies_count

In [28]:
mn = companies_count.mean()
mn

np.float64(1.4)

In [ ]:
# В городе "Технологополис" ежегодно проводится конференция разработчиков "DevFest". Для участия в
# мероприятии регистрируются сотни разработчиков, и каждый из них оставляет информацию о своем имени,
# уровне опыта (`junior`, `middle`, `senior`) и компании, в которой работает.

# Организаторы мероприятия попросили вас как главного аналитика проанализировать данные, чтобы узнать:

# - Какие уровни опыта представлены среди участников?
# - Сколько уникальных компаний представлено на конференции?
# - Какое среднее количество рабочих на компанию?

# Данные об участниках представлены в виде одномерных списков:

names = ["Анна", "Дмитрий", "Иван", "Анна", "Мария", "Сергей", "Дмитрий"]
companies = ["TechCorp", "DevSolutions", "CodeFactory", "TechCorp", "WebStudio", 
             "DataDrive", "CodeFactory"]
experience_levels = ["junior", "middle", "senior", "junior", "middle", "senior", "middle"]

In [30]:
df = pd.DataFrame({
    "Name": names, 
    "Company": companies,
    "Experience Level": experience_levels
}, index=["a", "b", "c", "d", "e", "f", "g"])
df

      Name       Company Experience Level
a     Анна      TechCorp           junior
b  Дмитрий  DevSolutions           middle
c     Иван   CodeFactory           senior
d     Анна      TechCorp           junior
e    Мария     WebStudio           middle
f   Сергей     DataDrive           senior
g  Дмитрий   CodeFactory           middle

In [35]:
df["Company"]["d"]

'TechCorp'

In [42]:
df.loc["e", "Company"]

'WebStudio'

In [46]:
df.loc[["a", "b"], ["Name", "Company"]]

      Name       Company
a     Анна      TechCorp
b  Дмитрий  DevSolutions

In [49]:
df.iloc[1:]

      Name       Company Experience Level
b  Дмитрий  DevSolutions           middle
c     Иван   CodeFactory           senior
d     Анна      TechCorp           junior
e    Мария     WebStudio           middle
f   Сергей     DataDrive           senior
g  Дмитрий   CodeFactory           middle