In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    "A": [1, np.nan, 2], 
    "B": [None, 3, 4],
    "C": [pd.NA, pd.NA, 5]
})

In [ ]:
df.isna()

In [ ]:
df.notna()

In [ ]:
df.isna().sum()

In [ ]:
df.notna().sum()

In [7]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [8]:
df.fillna(0)

C:\Users\Legionchik\AppData\Local\Temp\ipykernel_5396\516507702.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(0)

     A    B  C
0  1.0  0.0  0
1  0.0  3.0  0
2  2.0  4.0  5

In [9]:
df.fillna(df.mean())

C:\Users\Legionchik\AppData\Local\Temp\ipykernel_5396\634187881.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(df.mean())

     A    B    C
0  1.0  3.5  5.0
1  1.5  3.0  5.0
2  2.0  4.0  5.0